### ISSUE TITLE
Authentication request type seems wrong

### ISSUE THREAD

**Issue by creativefurniture** [spree/spree-storefront-api-v2-js-sdk#116]
We are building a Nuxt frontend for Spree. We are using official SDK (latest version) 
For authentication SDK sends OPTIONS request to backend and it gives 404. On documentation i see it shoult be POST request

## Context
Authentication request being sent to api/v2 with OPTIONS request and backend gives 404 for OPTIONS request. 

## Possible Fix
Change the request type to POST request

## Your Environment

* Library version: 
* Node and yarn/npm version: 
* Browser version: 
* Operating system:

**Comment by tniezg** [comment]
Hi 👋. `OPTIONS` requests are used for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Browsers send such requests to make sure the actual request can be performed. For Spree to accept all front-end requests issued by the Spree SDK, it's required to add a CORS configuration to it. This can be achieved by installing the [rack-cors](https://github.com/cyu/rack-cors) gem and following the guide [here](https://stackoverflow.com/a/31375871).
