### ISSUE TITLE
Account creation is documented but not supported by API

### ISSUE THREAD

**Issue by fauno** [spree/spree-storefront-api-v2-js-sdk#146]
Hi, I was just trying to create an account with `client.account.create()` as documented in the README but the API was responding with an infinite redirection. When I went to check the [API routes](https://github.com/spree/spree/blob/master/api/config/routes.rb#L152), there're only routes for getting account information, orders and credit cards, so now I'm confused. Could you clarify this is actually meant to be supported?

**Comment by damianlegawiec** [comment]
Hey @fauno please update `spree_auth_devise` to `4.2.0` to make those endpoints available
