### ISSUE TITLE
Request Function Sdk for Get All User Orders

### ISSUE THREAD

**Issue by fajaritsavirus** [spree/spree-storefront-api-v2-js-sdk#196]
**Is your feature request related to a problem? Please describe.**

Hi, I'm one of the developers who used your sdk. I got a problem when trying to Get All User Orders from your sdk, I've searched on your documentation and it seems that we don't capable to Get All User Orders by using your sdk.

**Describe the solution you'd like.**

Is it possible for you to develop this? to Get All User Orders by using your sdk

**Comment by tniezg** [comment]
@fajaritsavirus 👋 

Completed orders can be retrieved using https://github.com/spree/spree-storefront-api-v2-js-sdk#completedOrder and https://github.com/spree/spree-storefront-api-v2-js-sdk#completedOrdersList methods.

There's also https://github.com/spree/spree-storefront-api-v2-js-sdk#order which returns a specific placed order.

An order which isn't yet placed can be retrieved using https://github.com/spree/spree-storefront-api-v2-js-sdk#show for both signed in and guest users.

**Comment by fajaritsavirus** [comment]
@tniezg Hi, thanks a lot for the help,
I really misunderstood the meaning of completed orders methods, it works perfectly as I wanted
