### ISSUE TITLE
Request Filter Params on Get All User Orders

### ISSUE THREAD

**Issue by fajaritsavirus** [spree/spree-storefront-api-v2-js-sdk#197]
**Is your feature request related to a problem? Please describe.**

Hi, I'm one of the developers who used your platform Spree Commerce. I got a problem when trying to filtered out User Orders (shipment / payment status) from your API, I've searched on your documentation and it seems that we don't capable to filtered out User Orders.

**Describe the solution you'd like.**

Is it possible for you to develop this? to filtered out User Orders

**Additional context**

It would made the pagination better if the user has a lot of orders

**Comment by tniezg** [comment]
👋  Commented here: https://github.com/spree/spree-storefront-api-v2-js-sdk/issues/196
