### ISSUE TITLE
Add discontinue_on to the VariantAttributes object

### ISSUE THREAD

**Issue by JTimings** [spree/spree-storefront-api-v2-js-sdk#213]
**Is your feature request related to a problem? Please describe.**

Given discontinue_on is settable for a variant in admin panel it should be returned in VariantAttributes object

**Describe the solution you'd like.**

.

**Describe alternatives you've considered.**

.

**Additional context**

.

**Comment by tniezg** [comment]
Hi @JTimings 👋 ,
This is more a question to https://github.com/spree/spree. The Spree SDK parses results returned by Spree.

In any case, products can be filtered by `filter[show_discontinued]` to show all products, including those which are discontinued. The `discontinue_on` attribute can be easily added to APIv2 responses returning products or variants by decorating existing Spree models. I'm not convinced it's a good idea for Spree to return this value by default for products or variants. I think it isn't. I expect it's no coincidence that it's not returned by Spree right now.

You can try searching for discussions about product and variant serializers in the Spree repository. Chances are `discontinue_on` was already mentioned in those discussions. You can also post your suggestion in the Spree repository. It's more popular than the SDK.

Cheers,
T.
