### ISSUE TITLE
minified dist/server/index.js throws error with `next build`

### ISSUE THREAD

**Issue by ddombrowsky** [spree/spree-storefront-api-v2-js-sdk#244]
## Context

Please forgive my frustration, as I'm unsure where the root cause of this error even is.  

After upgrading spree SDK to latest (4.7.2), I am unable to build my site.  

To make a test build, I normally run `npx next build`, and that pre-compiles everything.

```
info  - Using external babel configuration from /home/davek/work/instinct/dna/dna-frontend/.babelrc
info  - Creating an optimized production build
Failed to compile.

./node_modules/@spree/storefront-api-v2-sdk/dist/server/index.js 1:521
Module parse failed: Unexpected token (1:521)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 

... minified js file removed ...

> Build error occurred
Error: > Build failed because of webpack errors
    at /home/davek/work/instinct/dna/dna-frontend/node_modules/next/dist/build/index.js:15:918
    at async /home/davek/work/instinct/dna/dna-frontend/node_modules/next/dist/build/tracer.js:1:1441


```

Does anyone have any idea what the root cause is?  I'm not even sure if it is babel or webpack or what is trying to parse this minified file, nor can I divine a configuration that will set it to be ignored from building (assuming that would even work, which it probably would not).

versions:
* webpack 4.46.0
* next 10.0.6
* storefront-api-v2-sdk 4.7.2

**Comment by ddombrowsky** [comment]
Note that pinning the build to use version `4.6.0` of `storefront-api-v2-sdk` _does_ work.  I'll have to do that in the meantime.

**Comment by tniezg** [comment]
Hi @ddombrowsky,
Thanks for creating the issue.

`./node_modules/@spree/storefront-api-v2-sdk/dist/server/index.js 1:521` contains optional chaining added in Spree SDK 4.7.0 (i.e. `?.`, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). We use the SDK with NextJS 11 and it works fine with that version. So, support for optional chaining was added between versions `10.0.6` and `11` of NextJS. Digging deeper, based on comments in Webpack's GitHub repo, Webpack 5 supports optional chaining and 4 doesn't (https://github.com/webpack/webpack/issues/10227).

We added optional chaining in just one place in the source code. We'll replace it with older syntax and release a new version of the SDK.

**Comment by tniezg** [comment]
https://github.com/spree/spree-storefront-api-v2-js-sdk/pull/245

**Comment by tniezg** [comment]
@ddombrowsky https://github.com/spree/spree-storefront-api-v2-js-sdk/releases/tag/v4.8.0. Let me know how the new version works for you.

**Comment by ddombrowsky** [comment]
@tniezg 
Wonderful!  Version `4.8.0` does indeed fix the build issue.  tyvm

**Comment by aforty** [comment]
This appears to be once again broken on v4.9.0.

**Comment by tniezg** [comment]
@aforty That's true! The new `src/helpers/jsonApi.ts` helper is the culprit. I'll fix that in `4.9.1`. Thank you for reporting the issue.

T.

**Comment by tniezg** [comment]
https://github.com/spree/spree-storefront-api-v2-js-sdk/pull/258

We'll release `4.9.1` today.

**Comment by tniezg** [comment]
https://github.com/spree/spree-storefront-api-v2-js-sdk/releases/tag/v4.10.0
