### ISSUE TITLE
Support for special non-english characters with URI component encoding

### ISSUE THREAD

**Issue by EstebanBorai** [spree/spree-storefront-api-v2-js-sdk#294]
Bring support to special characters used in Spanish such as the `ñ` letter for instance.

## Context

Currently when fetching the API using the SDK, the fetcher is not encoding URI components, this causes issues
on the backend.

```js
    const result = await storefrontSdkApiV2.taxons.show('api/v2/storefront/taxons/uñas', {
      include: 'parent',
    });
```

The `ñ` character is not being encoded as a URI component.
This is the `fetchOptions` object built from such function call:

```js
{
  url: 'api/v2/storefront/taxons/uñas',
  params: { include: 'parent' },
  method: 'get',
  headers: {},
  responseParsing: 'automatic'
}
```

Spree is not able to resolve the request because the letter `ñ` is not encoded to be URI compatible.

## Expected Behavior

URI components for paths/queries must be encoded, I've tested the SDK encoding the URI and got the expected response.

## Possible Fix

Encode URI path/query components before performing the request.

## Your Environment

* Library version: 4.12.0
* Node and yarn/npm version: v16.13.0
* Browser version: Safari Version 14.0.2
* Operating system: macOS v11.1

**Comment by tniezg** [comment]
We'll encode every custom parameter used in routes: https://github.com/spree/spree-storefront-api-v2-js-sdk/pull/297.

**Comment by tniezg** [comment]
Fixed in https://github.com/spree/spree-storefront-api-v2-js-sdk/releases/tag/v4.13.0
