### ISSUE TITLE
Compatibility issue with Expo

### ISSUE THREAD

**Issue by htorohn** [spree/spree-storefront-api-v2-js-sdk#45]
Hello,

I'm writing a mobile app with react native using the expo framework and when using this extension I'm getting the following error:

> The package at "node_modules/source-map-support/source-map-support.js" attempted to import the Node standard library module "path". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo

I installed the package using npm and this is my declaration inside my project

```
import { makeClient } from '@spree/storefront-api-v2-sdk'


const client = makeClient({
  host: MAIN_URL
})

```

Thanks for any help.

**Comment by tniezg** [comment]
Hi @htorohn,
Thanks for reporting the issue. It looks like your app is trying to use the `source-map-support` npm package and fails. `source-map-support` is strictly meant for use in a Node environment. As of now, we only support running the SDK in Node with plans to support more environments in the near future.

If you don't want to wait, you can try modifying `webpack.config.js`, remove `load-sourcemaps.js`, change the `target` to browser and rebuild the package by running `npm run build`. It may be enough to run the SDK in RN.

Hope this helps,
T.

**Comment by htorohn** [comment]
@tniezg thanks for your reply, I'll try your suggestion and let you know if it work!

**Comment by tniezg** [comment]
Versions >= 1.1.0 come with two bundles. One is for browsers and should cover the issue reported.
