### ISSUE TITLE
Fix /types regeneration when using `npm run watch`

### ISSUE THREAD

**Issue by tniezg** [spree/spree-storefront-api-v2-js-sdk#66]
## Context

Related to https://github.com/spree/spree-storefront-api-v2-js-sdk/issues/63. After initial bundle, every `.ts` file with just TS interfaces gets ignored. Since we started clearing /types before bundle regens, these files end up missing when developing the SDK and cause errors.

## Expected Behavior

- Force Webpack to regen all `.d.ts` files, including those with just interfaces.

## Possible Fixes

A. add generic `import <...>.ts` everywhere an interface file is loaded (maaaany places)
B. somehow fix how Webpack regens /types, but difficult due to issues reported in #63

## Your Environment

\-

**Comment by DustinRobison** [comment]
Using [create react app with typescript](https://facebook.github.io/create-react-app/docs/adding-typescript) has this issue.  Constant waiting on `Files successfully emitted, waiting for typecheck results...`

**Comment by tniezg** [comment]
Solved by https://www.staging-typescript.org/tsconfig#importsNotUsedAsValues (and updates to `ts-loader` 💪 ).
