### ISSUE TITLE
Host is resolving to localhost

### ISSUE THREAD

**Issue by gitstud** [spree/spree-storefront-api-v2-js-sdk#85]
## Context

```
const client = makeClient({
    host: 'https://madeup-api.herokuapp.com'
});

client.authentication.getToken({
    username: 'email@com.com',
    password: 'pass',
}).then(data => (console.log('result: ', data.fail(), data.success())))
```

I'm seeing this error below in the chrome console:
POST http://localhost:3000/spree_oauth/token
## Expected Behavior
POST https://madeup-api.herokuapp.com/spree_oauth/token

## Your Environment
Create-react-app

* Library version: 2.1.2
* Node and yarn/npm version:  yarn 1.13 node 10.13
* Browser version: latest chrome
* Operating system: osx

It seems like this is not working properly

in HTTPS
```this.host = process.env.SPREE_HOST || 'http://localhost:3000/'```

**Comment by tniezg** [comment]
Thanks for reporting!

Webpack freezes `process.env`. We'll create a fix.

**Comment by tniezg** [comment]
Should be fixed in `2.1.4`, please check.

**Comment by gitstud** [comment]
That did fix the localhost issue, requests are looking like this now

```xhr.js:173 POST http://localhost:3000/madeup-api.herokuapp.com/spree_oauth/token 404 (Not Found)```

**Comment by gitstud** [comment]
Thanks @tniezg !
